#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$SCRIPT_DIR/lib.sh"

bootstrap_repo

# Reserve a free loopback port for the backend; Vite proxies /api to it.
DJIT_DEV_API_PORT=$(mise_exec python -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()')
export DJIT_DEV_API_PORT
WEB_PID=""
API_PID=""
cleanup() {
  [ -z "$WEB_PID" ] || kill "$WEB_PID" 2>/dev/null || true
  [ -z "$API_PID" ] || kill "$API_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

cd "$REPO_ROOT/apps/server"
DJIT_ANALYSIS_WORKERS="${DJIT_ANALYSIS_WORKERS:-6}" \
  DJIT_ANALYSIS_DSP_CONCURRENCY="${DJIT_ANALYSIS_DSP_CONCURRENCY:-${DJIT_ANALYSIS_WORKERS:-6}}" \
  DJIT_SCAN_WORKERS="${DJIT_SCAN_WORKERS:-6}" \
  DJIT_ANALYSIS_ENGINE="${DJIT_ANALYSIS_ENGINE:-auto}" \
  DJIT_ANALYSIS_SAMPLE_RATE="${DJIT_ANALYSIS_SAMPLE_RATE:-22050}" \
  DJIT_ANALYSIS_MAX_DURATION_SECONDS="${DJIT_ANALYSIS_MAX_DURATION_SECONDS:-0}" \
  DJIT_ANALYSIS_KEY_PROFILE="${DJIT_ANALYSIS_KEY_PROFILE:-auto}" \
  DJIT_ANALYSIS_ENGINE_DJ_KEY_COMPAT="${DJIT_ANALYSIS_ENGINE_DJ_KEY_COMPAT:-1}" \
  DJIT_ANALYSIS_ENGINE_DJ_EDMM_PRIMARY="${DJIT_ANALYSIS_ENGINE_DJ_EDMM_PRIMARY:-1}" \
  DJIT_ANALYSIS_ENGINE_DJ_EDMM_PRIMARY_STRENGTH="${DJIT_ANALYSIS_ENGINE_DJ_EDMM_PRIMARY_STRENGTH:-0.62}" \
  DJIT_ANALYSIS_ENGINE_DJ_EDMM_PRIMARY_BOOST="${DJIT_ANALYSIS_ENGINE_DJ_EDMM_PRIMARY_BOOST:-1.6}" \
  DJIT_ANALYSIS_ENGINE_DJ_RELATIVE_MINOR_ON_LOW_CONF="${DJIT_ANALYSIS_ENGINE_DJ_RELATIVE_MINOR_ON_LOW_CONF:-1}" \
  DJIT_ANALYSIS_ENGINE_DJ_RELATIVE_MINOR_CONFIDENCE_THRESHOLD="${DJIT_ANALYSIS_ENGINE_DJ_RELATIVE_MINOR_CONFIDENCE_THRESHOLD:-0.56}" \
  DJIT_ANALYSIS_KEY_CORE_START_RATIO="${DJIT_ANALYSIS_KEY_CORE_START_RATIO:-0.20}" \
  DJIT_ANALYSIS_KEY_CORE_END_RATIO="${DJIT_ANALYSIS_KEY_CORE_END_RATIO:-0.85}" \
  DJIT_ANALYSIS_TEMPO_METHOD="${DJIT_ANALYSIS_TEMPO_METHOD:-multifeature}" \
  DJIT_ANALYSIS_HOP_LENGTH="${DJIT_ANALYSIS_HOP_LENGTH:-2048}" \
  OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}" \
  OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}" \
  MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}" \
  VECLIB_MAXIMUM_THREADS="${VECLIB_MAXIMUM_THREADS:-1}" \
  mise_exec uv run uvicorn djit.main:app --reload --host 127.0.0.1 --port "$DJIT_DEV_API_PORT" &
API_PID=$!

cd "$REPO_ROOT"
if command -v portless >/dev/null 2>&1; then
  portless run --name djit "$SCRIPT_DIR/mise-exec.sh" pnpm --filter web dev &
else
  mise_exec pnpm --filter web dev &
fi
WEB_PID=$!
wait "$WEB_PID"
